//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientsCommandes_Tp
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public int ComID { get; set; }
        public string Description { get; set; }
        public decimal Prix { get; set; }
        public Nullable<int> ClientId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
